// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "geminiApiKey": string;
      "openaiApiKey": string;
      "defaultModel": string;
      "geminiModels": string;
      "openaiModels": string;
      "enabledModels": string;
      "maxContextTokens": number;
      "defaultPromptId": string;
      "showSidebarOnStartup": boolean;
    };
  }
}
